from formatter.cover_page import add_cover_page
from formatter.styles import apply_document_style
from formatter.markdown_parser import add_markdown_runs

from core.utils.equation_renderer import add_equation

from docx import Document
from datetime import datetime
import os
import re


def create_report(title, content):

    os.makedirs(
        "outputs",
        exist_ok=True
    )

    doc = Document()

    # Apply styles
    apply_document_style(doc)

    # Cover page
    add_cover_page(
        doc,
        title
    )

    # Report info
    doc.add_paragraph(
        f"Generated by Athena AI\n"
        f"Date : {datetime.now().strftime('%d-%m-%Y %H:%M:%S')}"
    )

    doc.add_heading(
        "Report",
        level=2
    )


    for line in content.split("\n"):

        line = line.strip()

        if not line:
            continue


        if line.startswith("#### "):

            doc.add_heading(
                line[5:],
                level=4
            )


        elif line.startswith("### "):

            doc.add_heading(
                line[4:],
                level=3
            )


        elif line.startswith("## "):

            doc.add_heading(
                line[3:],
                level=2
            )


        elif line.startswith("# "):

            doc.add_heading(
                line[2:],
                level=1
            )


        elif line.startswith("- "):

            paragraph = doc.add_paragraph(
                style="List Bullet"
            )

            add_text_with_equations(
                paragraph,
                line[2:]
            )


        elif re.match(r"^\d+\.", line):

            text = re.sub(
                r"^\d+\.\s*",
                "",
                line
            )

            paragraph = doc.add_paragraph(
                style="List Number"
            )

            add_text_with_equations(
                paragraph,
                text
            )


        else:

            paragraph = doc.add_paragraph()

            add_text_with_equations(
                paragraph,
                line
            )


    filename = (
        f"outputs/{title.replace(' ', '_')}.docx"
    )

    doc.save(filename)

    return filename



def add_text_with_equations(paragraph, text):
    """
    Handles normal text + LaTeX + raw math equations
    """

    latex_pattern = r"(\$\$.*?\$\$|\$.*?\$)"

    parts = re.split(
        latex_pattern,
        text
    )

    for part in parts:

        if not part:
            continue


        if part.startswith("$"):

            add_equation(
                paragraph,
                part
            )

        elif contains_math(part):

            split_parts = split_raw_equations(part)

            for item in split_parts:

                if not item:
                    continue

                if contains_math(item):

                    add_equation(
                        paragraph,
                        item
                    )

                else:

                    add_markdown_runs(
                        paragraph,
                        item
                    )

        else:

            add_markdown_runs(
                paragraph,
                part
            )



def contains_math(text):

    indicators = [
        "∑",
        "√",
        "∞",
        "_{",
        "^{",
        "\\sum",
        "\\frac",
        "∈",
        "="
    ]

    return any(
        symbol in text
        for symbol in indicators
    )



def split_raw_equations(text):

    return re.split(
        r"(∑.*?(?=\s|$)|\\sum.*?(?=\s|$)|[A-Za-z]+_\{.*?\}|[A-Za-z]+_\w)",
        text
    )