from formatter.cover_page import add_cover_page
from formatter.styles import apply_document_style
from formatter.markdown_parser import add_markdown_runs

from docx import Document
from datetime import datetime
import os
import re


def create_report(title, content):
    os.makedirs("outputs", exist_ok=True)

    doc = Document()

    # Apply global styles
    apply_document_style(doc)

    # Add professional cover page
    add_cover_page(doc, title)

    # Report information
    doc.add_paragraph(
        f"Generated by Athena AI\n"
        f"Date : {datetime.now().strftime('%d-%m-%Y %H:%M:%S')}"
    )

    doc.add_heading("Report", level=2)

    # Parse markdown content
    for line in content.split("\n"):

        line = line.strip()

        if not line:
            continue

        # Heading 4
        if line.startswith("#### "):
            doc.add_heading(line[5:], level=4)

        # Heading 3
        elif line.startswith("### "):
            doc.add_heading(line[4:], level=3)

        # Heading 2
        elif line.startswith("## "):
            doc.add_heading(line[3:], level=2)

        # Heading 1
        elif line.startswith("# "):
            doc.add_heading(line[2:], level=1)

        # Bullet List
        elif line.startswith("- "):
            paragraph = doc.add_paragraph(style="List Bullet")
            add_markdown_runs(paragraph, line[2:])

        # Numbered List
        elif re.match(r"^\d+\.", line):
            text = re.sub(r"^\d+\.\s*", "", line)

            paragraph = doc.add_paragraph(style="List Number")
            add_markdown_runs(paragraph, text)

        # Normal Paragraph
        else:
            paragraph = doc.add_paragraph()
            add_markdown_runs(paragraph, line)

    # Save report
    filename = f"outputs/{title.replace(' ', '_')}.docx"

    doc.save(filename)

    return filename